version: '3.3'

services:
  teamspeak_app:
    image: teamspeak:3.13.6
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: teamspeak_db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: WD93w2gE5b
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept

  teamspeak_db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: WD93w2gE5b
      MYSQL_DATABASE: teamspeak